In [54]:
#https://sparkbyexamples.com/pandas/pandas-dataframe-where-examples/
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
import itertools
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
from sklearn.linear_model import PassiveAggressiveClassifier
import os

import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

In [55]:
df = pd.read_csv('C:/Users/DELL/Desktop/jobmela/studentdata.csv')
df=df.fillna(0)
df['BRANCH1']=df['BRANCH'].value_counts()
print(df['BRANCH'])

0      CSE 
1      CSE 
2      CSE 
3      CSE 
4      CSE 
       ... 
142     ECE
143     ECE
144       0
145       0
146       0
Name: BRANCH, Length: 147, dtype: object


In [56]:
filtered_values = np.where((df['BRANCH'].str.contains('CSE')) & (df['ACTIVE_Backlogs']==0)&(df['CERTIFICATIONS'].str.contains('AI'))&(df['EXTRA_CIRCULARS'].str.contains('Music'))&(df['PROJECTS_DONE'].str.contains('Yes')) )
print(filtered_values)         
display(df.loc[filtered_values])  
display(df.loc[filtered_values].count())

(array([0], dtype=int64),)


SL NO     ROLL NO                 STUDENT NAME BRANCH GENDER  \
0    1.0  19R11A0505  Mr. DUGGIRALA HIMAA SAMIIRR   CSE    Male   

            FATHERS NAME       D O B SSC%  INTER%  B.TECH%  ...  \
0  duggiralavenugopalrao  14-05-2002   73    70.5     70.0  ...   

        OFFICIAL EMAIL ID                PERSONAL EMAIL ID  \
0  19r11a0505@gcet.edu.in  duggiralahimaasameer@gmail.com    

  PLACED/Not Selected INTERNSHIPS PROJECTS_DONE EXTRA_CIRCULARS  \
0              Placed        Done           Yes           Music   

  CERTIFICATIONS Unnamed: 19 Unnamed: 20  BRANCH1  
0             AI         0.0         0.0      3.0  

[1 rows x 22 columns]

SL NO                  1
ROLL NO                1
STUDENT NAME           1
BRANCH                 1
GENDER                 1
FATHERS NAME           1
D O B                  1
SSC%                   1
INTER%                 1
B.TECH%                1
ACTIVE_Backlogs        1
CONTACT NO             1
OFFICIAL EMAIL ID      1
PERSONAL EMAIL ID      1
PLACED/Not Selected    1
INTERNSHIPS            1
PROJECTS_DONE          1
EXTRA_CIRCULARS        1
CERTIFICATIONS         1
Unnamed: 19            1
Unnamed: 20            1
BRANCH1                1
dtype: int64

In [57]:
df1 = pd.read_csv('C:/Users/DELL/Desktop/jobmela/studentdata1.csv')
df1=df1.fillna(0)
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df1.BRANCH = le.fit_transform(df1.BRANCH)
df1.GENDER = le.fit_transform(df1.GENDER)
df1.ACTIVE_Backlogs = le.fit_transform(df1.ACTIVE_Backlogs)
df1.INTERNSHIPS = le.fit_transform(df1.INTERNSHIPS)
df1.PROJECTS_DONE = le.fit_transform(df1.PROJECTS_DONE)
df1.EXTRA_CIRCULARS = le.fit_transform(df1.EXTRA_CIRCULARS)
df1.CERTIFICATIONS = le.fit_transform(df1.CERTIFICATIONS)



X1 = df1[['BRANCH','GENDER','ACTIVE_Backlogs','INTERNSHIPS','PROJECTS_DONE','EXTRA_CIRCULARS','CERTIFICATIONS']].values
X1
y1 = df1[['PLACED_OR_NOT_PLACED']]
y1
from sklearn.linear_model import LogisticRegression

X_train,X_test,y_train,y_test = train_test_split(X1,y1,test_size = 0.2)
from sklearn import linear_model
linear_clf = LogisticRegression()
linear_clf.fit(X_train, y_train)
pred = linear_clf.predict(X_test)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
print('confusion matrix')
print(confusion_matrix(y_test, pred))
#pred1 = linear_clf.predict(atest)
print(pred)
#print(pred1)
from sklearn.metrics import accuracy_score
print('accuracy')
print(accuracy_score(y_test, pred))


confusion matrix
[[22  1]
 [ 5  1]]
['Not Selected' 'Not Selected' 'Not Selected' 'Not Selected'
 'Not Selected' 'Not Selected' 'Placed' 'Not Selected' 'Not Selected'
 'Not Selected' 'Not Selected' 'Not Selected' 'Not Selected' 'Placed'
 'Not Selected' 'Not Selected' 'Not Selected' 'Not Selected'
 'Not Selected' 'Not Selected' 'Not Selected' 'Not Selected'
 'Not Selected' 'Not Selected' 'Not Selected' 'Not Selected'
 'Not Selected' 'Not Selected' 'Not Selected']
accuracy
0.7931034482758621


c:\users\dell\appdata\local\programs\python\python37\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
c:\users\dell\appdata\local\programs\python\python37\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [58]:
from sklearn.tree import DecisionTreeClassifier
X_train,X_test,y_train,y_test = train_test_split(X1,y1,test_size = 0.3)
from sklearn import linear_model
linear_clf = DecisionTreeClassifier()
linear_clf.fit(X_train, y_train)
pred = linear_clf.predict(X_test)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
print('confusion matrix')
print(confusion_matrix(y_test, pred))
#pred1 = linear_clf.predict(atest)
print(pred)
#print(pred1)
from sklearn.metrics import accuracy_score
print('accuracy')
print(accuracy_score(y_test, pred))


confusion matrix
[[20 10]
 [ 8  6]]
['Not Selected' 'Placed' 'Placed' 'Placed' 'Not Selected' 'Placed'
 'Not Selected' 'Not Selected' 'Not Selected' 'Not Selected'
 'Not Selected' 'Not Selected' 'Not Selected' 'Not Selected'
 'Not Selected' 'Not Selected' 'Not Selected' 'Placed' 'Placed' 'Placed'
 'Placed' 'Not Selected' 'Not Selected' 'Not Selected' 'Placed'
 'Not Selected' 'Not Selected' 'Placed' 'Not Selected' 'Not Selected'
 'Not Selected' 'Placed' 'Not Selected' 'Not Selected' 'Not Selected'
 'Placed' 'Placed' 'Placed' 'Placed' 'Not Selected' 'Not Selected'
 'Placed' 'Not Selected' 'Not Selected']
accuracy
0.5909090909090909


In [59]:
from sklearn.ensemble import RandomForestClassifier
linear_clf = RandomForestClassifier(n_estimators = 300, random_state = 0)
X_train,X_test,y_train,y_test = train_test_split(X1,y1,test_size = 0.3)

linear_clf.fit(X_train, y_train)
pred = linear_clf.predict(X_test)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
print('confusion matrix')
print(confusion_matrix(y_test, pred))
#pred1 = linear_clf.predict(atest)
print(pred)
#print(pred1)
from sklearn.metrics import accuracy_score
print('accuracy')
print(accuracy_score(y_test, pred))

c:\users\dell\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """
c:\users\dell\appdata\local\programs\python\python37\lib\site-packages\sklearn\utils\fixes.py:230: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if _joblib.__version__ >= LooseVersion('0.12'):


confusion matrix
[[28  2]
 [ 9  5]]
['Not Selected' 'Not Selected' 'Not Selected' 'Not Selected'
 'Not Selected' 'Not Selected' 'Not Selected' 'Not Selected'
 'Not Selected' 'Not Selected' 'Not Selected' 'Not Selected'
 'Not Selected' 'Not Selected' 'Not Selected' 'Not Selected' 'Placed'
 'Not Selected' 'Placed' 'Not Selected' 'Not Selected' 'Not Selected'
 'Not Selected' 'Not Selected' 'Not Selected' 'Not Selected'
 'Not Selected' 'Not Selected' 'Not Selected' 'Not Selected'
 'Not Selected' 'Not Selected' 'Not Selected' 'Not Selected' 'Placed'
 'Not Selected' 'Placed' 'Placed' 'Not Selected' 'Placed' 'Placed'
 'Not Selected' 'Not Selected' 'Not Selected']
accuracy
0.75


c:\users\dell\appdata\local\programs\python\python37\lib\site-packages\sklearn\utils\fixes.py:230: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if _joblib.__version__ >= LooseVersion('0.12'):


In [60]:
from sklearn.neighbors import KNeighborsClassifier
linear_clf1 = KNeighborsClassifier(n_neighbors=2)

X_train,X_test,y_train,y_test = train_test_split(X1,y1,test_size = 0.3)

linear_clf1.fit(X_train, y_train)
pred = linear_clf1.predict(X_test)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
print('confusion matrix')
print(confusion_matrix(y_test, pred))
#pred1 = linear_clf.predict(atest)
print(pred)
#print(pred1)
from sklearn.metrics import accuracy_score
print('accuracy')
print(accuracy_score(y_test, pred))

c:\users\dell\appdata\local\programs\python\python37\lib\site-packages\sklearn\neighbors\base.py:441: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  old_joblib = LooseVersion(joblib_version) < LooseVersion('0.12')
c:\users\dell\appdata\local\programs\python\python37\lib\site-packages\sklearn\neighbors\base.py:441: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  old_joblib = LooseVersion(joblib_version) < LooseVersion('0.12')


TypeError: unsupported operand type(s) for /: 'str' and 'int'